<a href="https://colab.research.google.com/github/bltsemih/User-Interface/blob/main/Finding_Most_Building_Counts_District.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from shapely.geometry import Polygon, LineString, Point

In [ ]:
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

Requirement already satisfied: libarchive in /usr/local/lib/python3.7/dist-packages (0.4.7)
Requirement already satisfied: nose in /usr/local/lib/python3.7/dist-packages (from libarchive) (1.3.7)

In [ ]:
pip install rtree

Requirement already satisfied: rtree in /usr/local/lib/python3.7/dist-packages (0.9.7)

In [ ]:
import rtree

In [ ]:
pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.20)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (3.2.0)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2021.5.30)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.2.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: munch in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2.8.2)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (1.19.5)

In [ ]:
import geopandas as gpd

In [ ]:
districts = gpd.read_file("districts.geojson")
buildings =  gpd.read_file("buildings.geojson")

In [ ]:
new = gpd.sjoin(districts,buildings,how="inner",op="intersects")
new["const"] = 1
new = new.groupby("gid_left").sum()
new = new.sort_values("const")

In [20]:
new

          index_right  gid_right  const
gid_left
9              739166    1025142     68
42             916126    1194540     72
40            1292024    1662651     87
24             601697     781875     92
7              227052     656977    105
54            1754754    2306380    119
17            1877732    2399072    130
37             422525     623520    142
50             671509    1354258    153
51             744134    1478711    161
21            2634962    3330820    175
14            1630818    2173423    175
52             893035    1694730    180
20            3553453    4345755    184
30             840707    1669356    192
22            4515625    5504390    209
47            1153331    1557026    209
31            1657583    2760455    237
38            4362383    5544703    244
27            3235254    4363855    246
3             4226519    5447835    276
10            5891434    7222007    292
34            4108549    5501956    292
41            4980592    6449215    314
16            6498473    8059707    332
44            9638751   11400389    358
35            4321501    5977842    367
48            6832884    8441719    370
33            3738174    5835226    448
11            8588682   10526122    463
29           12819282   15144039    481
39            6727395    9248698    543
26            3519187    6172292    566
49           12636148   15565094    610
36            5232175    8363145    644
5            10856717   13911244    653
53           15321169   18535340    659
46           14871847   18017244    666
12            4061469    7335114    697
13           13194961   16655306    736
4             3358658    6936871    779
25           20591331   24569741    814
32           16316772   20256105    815
23           10675272   14587739    838
57            4800932    8810161    861
1            12252662   16372030    871
18            8560702   12717286    894
56           24334035   28895722    950
45           15384472   20593104   1105
2            16365993   21661221   1120
43            4330623    8367059   1298
55           26617651   32760915   1308
19           17627124   24070354   1350
15           33007302   39744382   1382
28           16357145   23320375   1477
8            38072320   45720824   1584
6            55891848   65495916   1908

In [21]:
for e in list(new.index[-1:-4:-1]):
  print(districts.name[districts.gid == e].values[0], new.loc[e].const)

AYVANSARAY 1908
BALAT 1584
KOCAMUSTAFAPAŞA 1477